#!/usr/bin/env python3

## Simple runner

from afolders import default_dtn as dtn
import sys

if __name__ == "__main__":
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            dtn.start()
        elif 'stop' == sys.argv[1]:
            dtn.stop()
        elif 'restart' == sys.argv[1]:
            dtn.restart()
        else:
            print("Unknown command")
            sys.exit(2)
        sys.exit(0)
    else:
        print("Usage: %s start|stop|restart" % sys.argv[0])
        sys.exit(2)
